modLoader="javafml" #mandatory
loaderVersion="${loader_version_range}" #mandatory

license="GNU GPLv3"
issueTrackerURL="https://github.com/hammcmod/RadioCraft/issues" #optional

[[mods]] #mandatory
    modId="radiocraft" #mandatory
    version="${version}" #mandatory
    displayName="RadioCraft" #mandatory
    #updateJSONURL="https://change.me.example.invalid/updates.json" #optional
    #displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional
    logoFile="logo.png" #optional
    credits="Funded by the AARL" #optional
    authors="The RadioCraft Developers" #optional
    description='''RadioCraft'''

[[mixins]]
    config="radiocraft.mixins.json"


#[[accessTransformers]]
#   file="META-INF/accesstransformer.cfg"

[[dependencies.radiocraft]] #optional
    modId="neoforge" #mandatory
    type="required" #mandatory
    versionRange="${neo_version_range}" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.radiocraft]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.radiocraft]]
    modId="voicechat"
    mandatory=true
    versionRange="[${minecraft_version}-2.5.0,)"
    ordering="AFTER"
    side="BOTH"